version: '3.2'
services:
  elasticsearch:
    image: elasticsearch:7.13.2
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      discovery.type: single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - internal
    restart: unless-stopped
    
  logstash:
    image: logstash:7.13.2
    ports:
      - "5000:5000"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
      XPACK_MONITORING_ELASTICSEARCH_HOSTS: "elasticsearch:9200"
      XPACK_MONITORING_ENABLED: "true"
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    networks:
      - internal
    restart: unless-stopped
    depends_on:
      - elasticsearch

  kibana:
    image: kibana:7.13.2
    environment:
      XPACK_MONITORING_UI_CONTAINER_ELASTICSEARCH_ENABLED: "true"
    ports:
      - "5601:5601"
    networks:
      - internal
    restart: unless-stopped
    depends_on:
      - elasticsearch
      - logstash

networks:
  internal:

volumes:
  elasticsearch: